### ISSUE TITLE
Sort "incoming" flows by their origin labels

### ISSUE THREAD

**Issue by sandrotosi** [toobaz/mpl_sankey#2]
Hello,
i'm plotting how things evolve thru time, generating this diagram:

![Figure_2](https://user-images.githubusercontent.com/346648/106672706-7c434480-657e-11eb-9f66-8f50c0ec3669.png)

the 2 columns patches are sorted by their labels as you would expect, but let's look at the flows from 2021-02-01 to 2021-02-02: it would be more interesting to see that orange flow be right on top of the one coming from 2021-02-02, instead of being at the top of all the flows coming in 2021-02-02.

As in, i would expect that the order of incoming flows into a state, to be the same of their originating states

**Comment by toobaz** [comment]
> As in, i would expect that the order of incoming flows into a state, to be the same of their originating states

The default is to sort flows as they appear in the data. It is particularly sensible when you have more than one "phase", as otherwise flows on the left and on the right of a given node are mismatched.

This said, #3 should provide the behavior you are asking for, could you please test?

**Comment by sandrotosi** [comment]
Beautiful! this works exactly as i want it to:

![Figure_2_sorted](https://user-images.githubusercontent.com/346648/106836597-770df480-6667-11eb-9fd1-28e86e04b290.png)
