### ISSUE TITLE
Keyword arguments not recognized

### ISSUE THREAD

**Issue by fitzpk** [toobaz/mpl_sankey#7]
Love the library, just having some issues with the parameters. Using keyword arguments such as node_sizes and labels_size don't appear to work even with the minimal example provided. 

------------------------------------------------------------
from mpl_sankey import sankey
from matplotlib import pyplot as plt
import pandas as pd

data = pd.DataFrame([[1, 'a', 1, 'I', 1, 'success'],
                     [2, 'b', 2, 'III', 2, 'discard'],
                     [1, 'b', 1, 'II', 2, 'success'],
                     [1, 'c', 1, 'II', 2, 'discard'],
                     [2.5, 'a', 2, 'IV', 1, 'discard'],
                     [2, 'a', 1, 'I', 1, 'success']],
                    columns=['Weight', 'First', 'Then', 'After', 'Finally', 'Outcome'])
                    
plt.figure(figsize=(12, 3))
sankey(data, cmap=plt.get_cmap('viridis'), node_sizes=True)
plt.savefig('featured.png', bbox_inches='tight')

Results in the following error: TypeError: sankey() got an unexpected keyword argument 'node_sizes'

**Comment by toobaz** [comment]
I guess you're using version 0.0.1 (e.g. installed with pip)? It doesn't have the last changes. I will upload a new version soon - let's keep this issue open until then.

**Comment by fitzpk** [comment]
Yeah exactly right, I'm using version 0.0.1. Thanks for the hint on why it wasn't cooperating, will keep an eye out for the new upload!

**Comment by toobaz** [comment]
You can now find version 0.1.0 on pypi!
